WITH COUNTRY_ORDERS AS
(SELECT SHIP_COUNTRY,
		COUNT(*) AS NUMBER_OF_ORDERS
	FROM ORDERS
	GROUP BY SHIP_COUNTRY
	ORDER BY 2 DESC),
	
COUNTRY_ORDERS_MIN_MAX AS
(SELECT MIN(NUMBER_OF_ORDERS)
	FROM COUNTRY_ORDERS
UNION
SELECT MAX(NUMBER_OF_ORDERS)
	FROM COUNTRY_ORDERS)

SELECT * FROM COUNTRY_ORDERS WHERE NUMBER_OF_ORDERS IN (SELECT * FROM COUNTRY_ORDERS_MIN_MAX);
