-- Ranking of contries with most orders.
WITH ORDERS_COUNT AS
	(SELECT C.COUNTRY,COUNT(*) AS NUMBER_OF_ORDERS
		FROM ORDERS O
		INNER JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
		GROUP BY C.COUNTRY
		ORDER BY 2 DESC)
		
SELECT COUNTRY,
	RANK() OVER(ORDER BY NUMBER_OF_ORDERS DESC) AS ORDERS_RANKING,
	NUMBER_OF_ORDERS
FROM ORDERS_COUNT
ORDER BY NUMBER_OF_ORDERS DESC;
